const imagePaths = {
  home_tab: require('./home_tab.png'),
  mybooking_tab: require('./mybooking_tab.png'),
  message_tab: require('./message_tab.png'),
  profile_tab: require('./profile_tab.png'),

  email_icon: require('./email_icon.png'),
  eye_off_icon: require('./eye_off_icon.png'),
  eye_open:require('./eye_open.png'),
  lock_icon: require('./lock_icon.png'),
  login_img: require('./login_img.png'),
  signup_img: require('./signup_img.png'),
  google_icon: require('./google_icon.png'),
  fb_icon: require('./fb_icon.png'),
  insta_icon: require('./insta_icon.png'),
  forgot_img: require('./forgot_img.png'),
  otp_verify_img: require('./otp_verify_img.png'),
  pass_update_img:require('./pass_update_img.png'),
  mobile_icon:require('./mobile_icon.png'),
  app_icon:require('./app_icon.png'),
  
  heart_icon:require('./heart_icon.png'),
  calender_icon:require('./calender_icon.png'),
  notification_icon:require('./notification_icon.png'),
  down:require('./down.png'),
  filter_icon:require('./filter_icon.png'),
  banner1:require('./banner1.png'),
  banner2:require('./plumb_img.png'),

  carpentry:require('./carpentry.png'),
  cleaning:require('./cleaning.png'),
  cleaning2:require('./cleaning2.png'),
  painting:require('./painting.png'),
  plumb_img:require('./plumb_img.png'),
  electrical:require('./electrical.png'),
  verified_star:require('./verified_star.png'),
  star_filled:require('./star_filled.png'),
  service_logo1:require('./service_logo1.png'),
  service_loc:require('./service_loc.png'),
  money:require('./money.png'),
  ClockClockwise:require('./ClockClockwise.png'),
  recomanded1:require('./recomanded1.jpeg'),
  recomanded2:require('./recomanded2.jpeg'),
  recomanded3:require('./recomanded3.jpeg'),
  user_img:require('./user_img.png'),
  edit_profile:require('./edit_profile.png'),
  right_icon:require('./right_icon.png'),
  makup1:require('./makup1.jpeg'),
  siren:require('./siren.png'),
  search_h:require('./search_h.png'),
  filter_h:require('./filter_h.png'),
  US_flag:require('./US_flag.png'),
};
export default imagePaths;
