export const english = {
    login: {
      forgotPassword: 'Forget Password?',
      loginButton: 'Log in',
      orText: 'Or',
      dontHaveAccount: 'Don’t have an account?',
      signUp: ' Sign up',
    },
    signup: {
      signUpButton: 'Sign Up',
      alreadyHaveAccount: 'Already have an account?',
      logIn: 'Log In',
      orText: 'Or',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      acceptTerms: 'By signing up you accept the',
    },
    forgotpass:{
      forgotPassword: 'Forget Password',
      subtitle:  'Please enter the email id linked with your account',
      sendotp:'Send OTP',
    },
    otpverify:{
      title: 'Verification',
      subtitle:  'Please enter the code we sent to your email id',
      verify:'Verify',
    },
    updatepass:{
      title: 'Update Password',
      subtitle:  'Please create your new password',
      update:'Update',
    },
    placeholders: {
      email: 'Email',
      emailId: 'Email ID',
      password: 'Password',
      fullname: 'Full Name',
      mobileno: 'Mobile Number',
      reEnterPassword: 'Re-enter Password',
      confirmPassword: 'Confirm Password',
      currentPassword:'Current Password',
      createPassword:'Create Password',
      'AddNewAddress':'Add New Address',
      'save':'Save',
      'newPassword':'New Password',
    },

    validation: {
      fullNameMinLength: 'Full name must be at least 3 characters.',
      emptyFullName: 'Full name is required.',
      validFullName: 'Please enter a valid full name.',
      validEmail: 'Please enter a valid email address.',
      emptyEmail: 'Email is required.',
      validMobile: 'Please enter a valid mobile number.',
      mobileMinLen: 'Mobile number must be at least 10 digits.',
      emptyMobile: 'Mobile number is required.',
      passMinLength: 'Password must be at least 6 characters.',
      emptyPassword: 'Password is required.',

      passNewMinLength: 'New password must be at least 6 characters.',
      emptyNewPassword: 'New password is required.',

      passCurrMinLength: 'Current password must be at least 6 characters.',
      emptyCurrPassword: 'Current password is required.',

      emptyConfirmPassword: 'Confirm password is required.',
      notMatchConfirmPassword: 'Confirm password does not match.',
    },
    socialLogin: {
      google: 'Google button pressed',
      facebook: 'Facebook button pressed',
      instagram: 'Instagram button pressed',
    },
    profile:{
      'profileSetup': 'Profile Setup',
      'changePassword': 'Change Password',
      'myCalendar': 'My Calendar',
      'paymentHistory':'Payments',
      'paymentHistory1':'Payment History',
      'ratingsReviews': 'Ratings & Reviews',
      'loyaltyReferralDiscounts': 'Loyalty, Referral & Discounts',
      'multiLanguageCurrency': 'Multi-Language & Multi-Currency',
      'notificationsAlerts': 'Notifications & Alerts',
      'customerSupport': 'Customer Support',
      'logout': 'Logout',
      'headerTitle': 'Profile Menu',
      'languageSettings': 'Language Settings',
    },
    languageSetting:{
      supportSection:'Support Section',
      language:'Language',
      currencyConverter:'Currency Converter',
      currencySwitcher:'Currency Switcher',
    },
  };
